### PR TITLE
Simple BLE

### PR DESCRIPTION
**Pull request by thegecko**
Switch backend to use SimpleBLE

### CODE REVIEW

**Comment by RReverser** [comment]
Just tried this branch on Windows and it was so much easier to get going with it than the published version. Can't wait for it to get published.

**Comment by RReverser** [comment]
> Can't wait for it to become upstream :)

FWIW I fried the device board in an unrelated accident since writing this comment, so looks like I _can_ wait after all 😅

**Comment by thegecko** [comment]
@symbitic I'm preparing this branch for merging into master. I've reflected the current implementation status in the [README](https://github.com/thegecko/webbluetooth/blob/simple-ble/README.md) along with any missing functionality.

The major area missing before release (which is already implemented in the noble version) is characteristic notify/indicate support which I'm having trouble with.

I'm currently getting the following error:

```bash
#
# Fatal error in v8::HandleScope::CreateHandle()
# Cannot create a handle without a HandleScope
#
```

When using this test script:

https://gist.github.com/thegecko/4077b47fc6b23be99881d9b47d49ca6d

Could you see if you can identify the problem? I have confirmed `simplepyble` works as expected, so believe its the Node wrapping code.

**Comment by Symbitic** [comment]
Did you check my latest C++ bindings? I had that problem in most of the callbacks a while back. Otherwise, I'll take a look soon.

**Comment by thegecko** [comment]
> Did you check my latest C++ bindings?

Hmm I'm not using the latest ones, I seem to remember I had an issue previously, so tried again.

Updated this branch to use the bindings from your last commit in January and get a segfault when calling `simpleble_adapter_scan_start`

**Comment by Symbitic** [comment]
Okay. I'll take a look soon.

**Comment by thegecko** [comment]
Just tried swapping theExternal handles back to BIGINTs and it works again. I get a different error with notify callbacks now :)

#
# Fatal error in HandleScope::HandleScope
# Entering the V8 API without proper locking in place
#

**Comment by Symbitic** [comment]
I think the BigInt/External changes were what fixed callbacks for me.

**Comment by thegecko** [comment]
> I think the BigInt/External changes were what fixed callbacks for me.

OK, let me try something...

**Comment by thegecko** [comment]
> OK, let me try something...

No joy, I got the bindings on this branch as close to your version as possible but still get

```bash
#
# Fatal error in HandleScope::HandleScope
# Entering the V8 API without proper locking in place
#
```

What platform do you test on?

**Comment by Symbitic** [comment]
I just updated the bindings in my branch. Adapter callbacks work, but not peripheral for some reason. I verified the CPP callback is being called, but not the JS. `tsfn.NonBlockingCall` does nothing. Filed a bug report with node-addon-api to see if I can figure out what's up.

**Comment by thegecko** [comment]
Once we have the peripheral callbacks working, I think this branch is ready to be merged and released.

**Comment by thegecko** [comment]
> I just updated the bindings in my branch. Adapter callbacks work, but not peripheral for some reason. I verified the CPP callback is being called, but not the JS. tsfn.NonBlockingCall does nothing. Filed a bug report with node-addon-api to see if I can figure out what's up.

Any joy with this?

**Comment by Symbitic** [comment]
> Any joy with this?

I think I got it! Check my latest branch. It took no small amount of effort, but I confirmed that peripheral callbacks like connected/disconnected are working.

One note: I'm testing on Linux. I did get `Fatal error in HandleScope::HandleScope` once, but I had to really abuse this for that to happen.

**Comment by thegecko** [comment]
> I think I got it! Check my latest branch.

Cool, could you link me to it? I had a nose around but couldn't see any changes on your PR here nor your fork.

**Comment by Symbitic** [comment]
Sorry, forgot to push. It's in my simpleble-port branch.

**Comment by thegecko** [comment]
Erk, was hoping for a drop-in fix with some wiring, but it looks like the entire cpp interface has changed :/

**Comment by Symbitic** [comment]
Yeah, sorry. Objects turned out to be necessary because the only way to get callbacks to work was with function references.

If you don't want to change your code, I can make whatever changes you want to my branch so you can merge it. I changed it so that `new Bluetooth` works by making it work closer to yours (`adapters.ts` exports an array of adapters which the constructor in Bluetooth uses).

**Comment by thegecko** [comment]
> Sorry, forgot to push. It's in my simpleble-port branch.

Thanks, I have grabbed your latest bindings and updated these on this branch:

https://github.com/thegecko/webbluetooth/tree/simple-ble-update

Although everything compiles, I'm getting this error when a device is found:

```
#
# Fatal error in HandleScope::HandleScope
# Entering the V8 API without proper locking in place
#
```

I seem to remember having this issue before when using the found callback so the adapter previously used the [simpleble_adapter_scan_get_results_handle](https://github.com/thegecko/webbluetooth/blob/simple-ble/src/adapters/simpleble-adapter.ts#L125) instead.

Your new API no longer exposes this method, so I'll see if I can fix the issue...

**Comment by thegecko** [comment]
UPDATE: Just found the `peripherals` property, d'oh!

**Comment by thegecko** [comment]
OK, so I have your latest updates in to this branch and working as well as before. I much prefer this interface, very clean 👍 

Unfortunately I still see errors for the `found`, `indicate` and `notify` callbacks when triggered:

```
#
# Fatal error in HandleScope::HandleScope
# Entering the V8 API without proper locking in place
#
```

I'm still using polling to get round the `found` issue, but have no workarounds for `indicate`/`notify`.

BTW, I had to fix a couple of issues in your code.

Info is zero-based:
https://github.com/thegecko/webbluetooth/pull/47/commits/f3b0650135b9bdad66f849d1bf70952020a72eae

UUIDs need the termination character removed before passing to TypeScript:
https://github.com/thegecko/webbluetooth/pull/47/commits/2f254290cccba928ab8f411527fcef07409f64e6

Any other ideas for fixing these callback issues?

**Comment by Symbitic** [comment]
I'll take a look. I'm on vacation, so I don't have access to a Windows laptop. I'll definitely keep working on this, though. Can you try building my branch and see if it has the same error? That will help narrow it down. If you still do, I'll send you some debug statements to add to peripheral.cpp to identify where the problem is.

**Comment by thegecko** [comment]
> I'll take a look. I'm on vacation, so I don't have access to a Windows laptop. I'll definitely keep working on this, though. Can you try building my branch and see if it has the same error? That will help narrow it down. If you still do, I'll send you some debug statements to add to peripheral.cpp to identify where the problem is.

My Windows machine doesn't have bluetooth so all my dev/testing is done on macOS.

I tried your branch. I can build it, but can't work out how to run anything due to the module system

```
> deno run examples/deno/scan.ts  
error: Module not found "file:///.../webbluetooth/mod.ts".
    at file:///.../webbluetooth/examples/deno/scan.ts:3:26
```

```
> node examples/selector.js                             
file:///.../webbluetooth/examples/selector.js:86
const bluetooth = new Bluetooth({ deviceFound });
      ^

SyntaxError: Identifier 'bluetooth' has already been declared
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:115:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:289:14)
    at async link (node:internal/modules/esm/module_job:70:21)
```

```
> ts-node --esm examples/scan.ts                        
Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:readline/promises
    at new NodeError (node:internal/errors:371:5)
    at ESMLoader.builtinStrategy (node:internal/modules/esm/translators:258:11)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:289:14) {
  code: 'ERR_UNKNOWN_BUILTIN_MODULE'
```

As the `lib` folder between our branchs are the same, I would expect to see the same issues if I got this running.

**Comment by Symbitic** [comment]
The Deno port is not working at all ATM in my branch (I decided to wait until I got the Node stuff finished). The `selector.js` example in my branch isn't working because the scan in `Bluetooth` class doesn't use `new Promise` so `selectFn` won't work.

Which version of Node.js are you using? `node:readline/promises` was added in v12 and became stable in v14. I suppose I could remove that and use the older version of readline if needed.

 I am getting that V8 error when using your branch. Looking into it. This would all have been so much easier if ThreadSafeFunction just worked.

**Comment by Symbitic** [comment]
I think I finally got it! The problem with ThreadSafeFunction was that it would block the program from exiting. I managed to solve that with HandleScope and Unref. There can sometimes be a delay (<1s) but all callbacks, including `setCallbackOnScanStart` and `setCallbackOnConnected` worked for me.

Should be much safer now that it's using TSFN.

**Comment by thegecko** [comment]
Nice work! I tried your update earlier and saw callbacks working. I'll update the link and tests on this branch.

**Comment by thegecko** [comment]
Thanks to the awesome efforts from @Symbitic , this is ready to be merged. I'll leave it open for a few days for comment.

**Comment by Symbitic** [comment]
I think this looks great! Good job!

I'll close my PR and start a new fork to start adding things incrementally, like removing Node-specific things like EventEmitter so I can start on Deno compatibility later. For now, the important thing is: **webbluetooth no longer requires sudo on Linux and installing custom drivers on Windows!** :partying_face:

**Comment by thegecko** [comment]
[webbluetooth@3.0.2](https://www.npmjs.com/package/webbluetooth) has just been released containing the new SimpleBLE backend.

I've tested this on MacOS (the only system I have access to), would love to hear how this works for others!

**Comment by Symbitic** [comment]
Tested on Linux. Looks good to me.

**Pull request merged**
