### PR TITLE
Allow local build

### LINKED ISSUE #179: Build error on raspberry 4
When using webbluetooth I get (after installing cmake):

```
ingof@raspi16g:~/official-matter.js$ npm i
npm ERR! code 1
npm ERR! path /home/ingof/official-matter.js/node_modules/webbluetooth
npm ERR! command failed
npm ERR! command sh -c prebuild-install --backend cmake-js --runtime napi || cmake-js rebuild
npm ERR! Not searching for unused variables given on the command line.
npm ERR! -- The C compiler identification is GNU 11.4.0
npm ERR! -- The CXX compiler identification is GNU 11.4.0
npm ERR! -- Detecting C compiler ABI info
npm ERR! -- Detecting C compiler ABI info - done
npm ERR! -- Check for working C compiler: /usr/bin/cc - skipped
npm ERR! -- Detecting C compile features
npm ERR! -- Detecting C compile features - done
npm ERR! -- Detecting CXX compiler ABI info
npm ERR! -- Detecting CXX compiler ABI info - done
npm ERR! -- Check for working CXX compiler: /usr/bin/c++ - skipped
npm ERR! -- Detecting CXX compile features
npm ERR! -- Detecting CXX compile features - done
npm ERR! -- Configuring incomplete, errors occurred!
npm ERR! See also "/home/ingof/official-matter.js/node_modules/webbluetooth/build/CMakeFiles/CMakeOutput.log".
npm ERR! prebuild-install warn install No prebuilt binaries found (target=6 runtime=napi arch=arm64 libc= platform=linux)
npm ERR! info TOOL Using Unix Makefiles generator.
npm ERR! info CMD CLEAN
npm ERR! info RUN [
npm ERR! info RUN   'cmake',
npm ERR! info RUN   '-E',
npm ERR! info RUN   'remove_directory',
npm ERR! info RUN   '/home/ingof/official-matter.js/node_modules/webbluetooth/build'
npm ERR! info RUN ]
npm ERR! info CMD CONFIGURE
npm ERR! info RUN [
npm ERR! info RUN   'cmake',
npm ERR! info RUN   '/home/ingof/official-matter.js/node_modules/webbluetooth',
npm ERR! info RUN   '--no-warn-unused-cli',
npm ERR! info RUN   '-G',
npm ERR! info RUN   'Unix Makefiles',
npm ERR! info RUN   '-DCMAKE_JS_VERSION=7.3.0',
npm ERR! info RUN   '-DCMAKE_BUILD_TYPE=Release',
npm ERR! info RUN   '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ingof/official-matter.js/node_modules/webbluetooth/build/Release',
npm ERR! info RUN   '-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded$<$<CONFIG:Debug>:Debug>',
npm ERR! info RUN   '-DCMAKE_JS_INC=/home/ingof/official-matter.js/node_modules/node-api-headers/include;/home/ingof/official-matter.js/node_modules/webbluetooth/node_modules/node-addon-api',
npm ERR! info RUN   '-DCMAKE_JS_SRC=',
npm ERR! info RUN   '-DNODE_RUNTIME=node',
npm ERR! info RUN   '-DNODE_RUNTIMEVERSION=18.17.1',
npm ERR! info RUN   '-DNODE_ARCH=arm64',
npm ERR! info RUN   '-DCMAKE_JS_LIB=',
npm ERR! info RUN   '-DCMAKE_CXX_FLAGS=-DBUILDING_NODE_EXTENSION'
npm ERR! info RUN ]
npm ERR! CMake Error at CMakeLists.txt:14 (add_subdirectory):
npm ERR!   add_subdirectory given source "SimpleBLE/simpleble" which is not an
npm ERR!   existing directory.
npm ERR! 
npm ERR! 
npm ERR! ERR! OMG Process terminated: 1

npm ERR! A complete log of this run can be found in: /home/ingof/.npm/_logs/2024-03-23T16_03_00_266Z-debug-0.log
```

It seems that SimpleBLE is not delivered as source files in the npm package -.. which is true ... https://github.com/thegecko/webbluetooth/blob/master/.npmignore#L4

SHould it be added to allow fallback local builds?

### PR DESCRIPTION
**Pull request by Apollon77**
This PR adds the SimpleBLE directory and all sub dirs to the npm package. I verified with publish dry run" that it would be added to the package and validated that it can install on a raspi 4 with an "npm pack" version of that.

BTW: A GitHub install would _not_ check the SimpleBLE directory out and so would not work here!

Means: I could test it only with npm pack

fixes #179 

PS: The PR contains two extra commits from trying to get more debug infos, just squash&merge it ...

### CODE REVIEW

**Comment by thegecko** [comment]
If the source isn't coming from the package (this PR isnt released yet) then you need to clone it in. As SimpleBLE is a submodule, you'll need to clone it recursively.

**Comment by Apollon77** [comment]
Iiinteresting ... yes now I see that really files are missing ... grmpff ... ok will pay areound further

**Comment by Apollon77** [comment]
Ahhhh ... I found it ... the "src" in npmignore caused the SimpleBLE/simpleble/src* to be excluded from the npm pack ... I will verify

**Comment by Apollon77** [comment]
@thegecko ok with these changes I was able to install it via an "npm pack" version on my raspi

>ingof@raspi16g:~/test$ npm i webbluetooth-3.2.1.tgz 
>
>added 98 packages in 12m

Took ages, but worked :-)

I updated the first comment her ein this PR

**Comment by thegecko** [comment]
The '/' you've added forces the ignore match to only see the ones in the root folder.

I think your change only needs to remove the `src` and `SimpleBLE` entries.

**Comment by Apollon77** [comment]
I added the "/" because I assumed that these folders should only exist on root level and so this should be more accurate to prevent the case that there are unwanted sub dirs excluded.
And removing src from the list the src on root would been included in the resulting package which I also thought that ot is a reason that this should not be.

I can adjust as you said if you want that way, but maybe reconsider with infos above.

**Comment by thegecko** [comment]
Please keep this PR for the original intent. Changing other inclusions may have undesired side effects and requires further testing

**Comment by Apollon77** [comment]
Allright, adjusted, if you are ok with the side effect now that Typescript files in src on root will now also be published on npm (that lso has it's benefits in my eyes) ;-)

**Comment by Apollon77** [comment]
PS: Depending what you want we could also just use /src to still exclude src on root level as it was before. your decision

**Review by thegecko — APPROVED** [review]

**Comment by thegecko** [comment]
LGTM, thanks!

**Pull request merged**
